os: linux
dist: xenial
language: python
python:
  - "3.6.6"
install:
  - pip install -r requirements.txt

#services:
#  - couchdb

#before_script:
#  - curl -X PUT localhost:5984/structures-test
#  - curl -X PUT localhost:5984/limits-test
#  - curl -X PUT localhost:5984/events-test
#  - curl -X PUT localhost:5984/requests-test
#  - curl localhost:5984

before_install:
    - pip install pytest pytest-cov
    - pip install coveralls

script:
  - python3.6 -m unittest Guardian/testGuardian.py
  - python3.6 -m unittest MyUtils/testMyUtils.py
#  - python3.6 -m unittest StateDatabase/testcouchDB.py

after_success:
    - coveralls