os: linux
dist: xenial
language: python
python:
  - "3.6.6"
install:
  - pip install -r requirements.txt

services:
  - couchdb

script:
  - python3.6 -m unittest Guardian/testGuardian.py MyUtils/testMyUtils.py StateDatabase/testcouchDB.py

