site_name: Serverless Containers documentation
nav:
    - Home: index.md
    - Use case: use_case.md
    - Architecture: architecture.md
    - Deployment: deployment.md
    - Source code: code/src/index.html
    - Sponsors: sponsors.md

#theme: readthedocs
#theme: mkdocs

theme:
    name: material
    #custom_dir: 'custom_theme/'
    favicon: 'img/favicon.ico'


# Repository
repo_name: 'JonatanEnes/ServerlessContainers'
repo_url: 'https://github.com/JonatanEnes/ServerlessContainers'

# Copyright
copyright: 'Copyright &copy; 2018 - 2020 Jonatan Enes'

markdown_extensions:
  - attr_list